[project]
name = "dz-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3==1.37.22",
    "mlflow==2.17.2",
    "pandas==2.0.3",
    "psycopg2-binary==2.9.10",
    "pyspark==3.0.3",
    "scikit-learn==1.3.2",
]
